cartesian_position_controller:
    ros__parameters:
        # Control output mode of the controller. Can be one of [0 - twist , 1 - acceleration].
        control_mode: 0
        # Name of the WBC task this controller is assigned to.
        task_name: ee_pose
        # Node name of the WBC controller.
        wbc_name: whole_body_controller
        # P-Gain of the controller, size has to be 6.
        p_gain: [10.0,10.0,10.0,10.0,10.0,10.0]
        # D-Gain of the controller, size has to be 6. In case of velcity control mode, this is the feed forward gain
        d_gain: [0.0,0.0,0.0,0.0,0.0,0.0]
        # Controller output saturation per element. Size has to be 6.
        max_control_output: [10.0,10.0,10.0,10.0,10.0,10.0]
