/kuka_iiwa/wbc/ee_pose/trajectory:
  ros__parameters:
    amplitude: 0.1
    plane: "xy"
    init_pos_x: 0.0
    init_pos_y: 0.0
    init_pos_z: 1.1
    init_ori_qx: 0.0
    init_ori_qy: -0.707
    init_ori_qz: 0.0        
    init_ori_qw: 0.707
