controller_manager:
    ros__parameters:
        # Update rate in Hz. This is the update rate of the controller manager. However, if you don' t configure the update rate for any of the 
        # controllers, every controller will run at this rate
        update_rate: 1000 
        # Type configuration for the joint state broadcaster
        joint_state_broadcaster:
          type: joint_state_broadcaster/JointStateBroadcaster
        # Type configuration for the whole body controller
        position_controller:
          type: joint_trajectory_controller/JointTrajectoryController

position_controller:
    ros__parameters:
        # State interfaces provided by the hardware for all joints
        state_interfaces: ["position"]
        # Command interfaces provided by the hardware interface for all joints
        command_interfaces: ["position"]
        # Names of the joints to control
        joints: ["joint_a1","joint_a2","joint_a3","joint_a4","joint_a5","joint_a6","joint_a7"]
      