/cartesian_trajectory_publisher:
  ros__parameters:
    # Amplitude of the circular trajectory in x-direction
    amplitude_x: 0.1
    # Amplitude of the circular trajectory in y-direction
    amplitude_y: 0.1
    # Frequency of the circular trajectory
    frequency: 0.3
    # Plane in which the trajectory should be executed, cyn be one of [xy,yz,xz]
    plane: "xy"
    # Initial position x of the robot
    init_pos_x: 0.067
    # Initial position y of the robot
    init_pos_y: 0.0
    # Initial position z of the robot
    init_pos_z: 1.138
    # Initial orientation qx of the robot
    init_ori_qx: 0.0
    # Initial orientation qy of the robot
    init_ori_qy: 0.0
    # Initial orientation qz of the robot
    init_ori_qz: 0.0
    # Initial orientation qw of the robot
    init_ori_qw: 1.0
