whole_body_controller:
    ros__parameters:
        task_names: ["ee_pose"]
        robot_model:
            type: rbdl
        task_config:
            ee_pose:
                type: 1
                priority: 0
                root: world
                tip: link_ee
                ref_frame: world
                weights: [1.0,1.0,1.0,1.0,1.0,1.0]
                activation: 1.0
        solver_config:
            type: qpoases
        scene_config:
            type: velocity_qp
        integrate: true
