controller_manager:
    ros__parameters:
        # Update rate in Hz. This is the update rate of the controller manager. However, if you don' t configure the update rate for any of the 
        # controllers, every controller will run at this rate
        update_rate: 1000 
        # Type configuration for the joint state broadcaster
        joint_state_broadcaster:
          type: joint_state_broadcaster/JointStateBroadcaster
        # Type configuration for the whole body controller
        whole_body_controller:
          type: wbc_ros/WholeBodyController
        # Type configuration for the CoM position controller
        com_position_controller:
          type: wbc_ros/CoMPositionController

whole_body_controller:
    ros__parameters:
        # Update rate in Hz. 
        update_rate: 1000
        # Control mode of the wbc. Can be one of 0 - velocity, 1 - acceleration.
        control_mode: 1
        # Command interfaces to claim from hardware. Can be one of [position,velocity,effort]
        command_interfaces: ["position", "velocity"]
        # State interfaces to claim from hardware. Can be one of [position,velocity,effort,acceleration]
        state_interfaces: ["position", "velocity"]
        # Names of the tasks to be configured in task configuration. Each task will be a summand in the QP solver's cost function.
        task_names: ["com_position", "fr_leg_position"]
        # Prefix used in the robot description parameter to claim the correct state and command interface names.
        prefix: ""
        # The joint weights control the contribution of each individual joint to the solution. Values have to be within [0,1].
        # A zero means here that the joint is not used at all. Size has to be same as number of robot joints.
        joint_weights: [1.0,1.0,1.0,1.0,1.0,1.0,1.0]
        robot_model:
            # Absolute path to plain URDF file of the robot
            file: install/wbc_ros/share/wbc_ros/models/urdf/kuka/iiwa.urdf
            # Robot model type. Must be the exact name of one of the registered robot model plugins. See src/robot_models for all available plugins. Default is pinocchio
            type: pinocchio
            # Does the robot have a floating base? Attaches a virtual 6 DoF floating base to the model, default is false
            floating_base: false
        tasks:
            com_position:
                # Task type, can be one of [spatial_velocity, spatial_acceleration, com_velocity, com_acceleration, joint_velocity, joint_acceleration, contact_forces]
                type: com_acceleration
                # Priority of this task. 0 corresponds to the highest priority. Prioritization is only supported by the hls solver.
                priority: 0
                # Initial weights for this task. Size has to be same as number of task variables, e.g. number of joint names in joint space tasks.
                # and 6 in case of a Cartesian task. All entries have to be >= 0.  Can be used to balance contributions of the task variables.
                # A value of 0 means that the reference of the corresponding task variable will be ignored while computing the solution.
                weights: [1.0,1.0,1.0]
                # Initial activation for this task. Has to be within 0 and 1. Can be used to enable(1)/disable(0) the whole task,
                # or to apply a smooth activation function.
                activation: 1.0
            fr_leg_position:
                # Task type, can be one of [spatial_velocity, spatial_acceleration, com_velocity, com_acceleration, joint_velocity, joint_acceleration, contact_forces]
                type: spatial_acceleration
                # Priority of this task. 0 corresponds to the highest priority. Prioritization is only supported by the hls solver.
                priority: 0
                # Only Cartesian tasks: Tip frame of the kinematic chain associated with this task. Has to be the name of a valid link in the robot model.
                tip_frame: FR_foot
                # Only Cartesian tasks: Reference frame of the task input (frame wrt which the input is expressed).
                # This has to be the name of a valid link in robot model. If ref_frame != root the input will be transformed to the root frame.
                ref_frame: base
                # Initial weights for this task. Size has to be same as number of task variables, e.g. number of joint names in joint space tasks.
                # and 6 in case of a Cartesian task. All entries have to be >= 0.  Can be used to balance contributions of the task variables.
                # A value of 0 means that the reference of the corresponding task variable will be ignored while computing the solution.
                weights: [1.0,1.0,1.0,1.0,1.0,1.0]
                # Initial activation for this task. Has to be within 0 and 1. Can be used to enable(1)/disable(0) the whole task,
                # or to apply a smooth activation function.
                activation: 1.0                
        solver:
            # QP Solver type. Must be the exact name of one of the registered QP solver plugins. See src/solvers for all available plugins. Default is qpoases
            type: qpoases
        scene:
            # Scene type. Must be the exact name of one of the registered scene plugins. See src/scenes for all available plugins.
            type: acceleration_tsid
        # Do numerical integration on the solver output, e.g. if output is acceleration type, integrate twice to get velocity and position
        integrate: true

com_position_controller:
    ros__parameters:
        # Control output mode of the controller. Can be one of [0 - twist , 1 - acceleration].
        control_mode: 1
        # Name of the WBC task this controller is assigned to.
        task_name: com_position
        # Node name of the WBC controller.
        wbc_name: whole_body_controller
        # P-Gain of the controller, size has to be 6.
        p_gain: [5.0,5.0,5.0]
        # D-Gain of the controller, size has to be 6. In case of velcity control mode, this is the feed forward gain
        d_gain: [3.0,3.0,3.0]
        # Controller output saturation per element. Size has to be 6.
        max_control_output: [10.0,10.0,10.0]        