/joint_trajectory_publisher:
  ros__parameters:
    # Amplitude of the sine/cosine curve
    amplitude: 0.3
    # Frequency of the sine/cosine curve
    frequency: 3.0
    # Joint names used in the trajectory
    joint_names: ["joint_a1", "joint_a2", "joint_a3", "joint_a4", "joint_a5", "joint_a6", "joint_a7"]
    # Initial position  of all joints
    initial_positions:
      joint_a1: 0.0
      joint_a2: 0.7854
      joint_a3: 0.0
      joint_a4: 1.3962
      joint_a5: 0.0
      joint_a6: 0.6109
      joint_a7: 0.0
