/kuka_iiwa/joints:
  ros__parameters:
    noise_std_dev: 1e-4
    initial_joint_state:
        name: ["joint_0","joint_1","joint_2","joint_3","joint_4","joint_5","joint_6"]
        position: [0.0,0.5,0.0,1.0,0.0,0.5,0.0]
        velocity: [0.0,0.0,0.0,0.0,0.0,0.0,0.0]
        effort: [0.0,0.0,0.0,0.0,0.0,0.0,0.0]
