name: Ubuntu 22.04

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test_22_04:
    runs-on: ubuntu-22.04

    steps:
    # Check out repository under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2
    # Build and install
    - name: install
      run: |
       sudo apt install software-properties-common
       sudo add-apt-repository universe
       sudo apt update && sudo apt install curl -y
       sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
       echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
       sudo apt update
       sudo apt install ros-humble-ros-base
       sudo apt install ros-dev-tools       
       source /opt/ros/humble/setup.bash  
         
       sudo rosdep init
       rosdep update   
     
       git clone https://github.com/ARC-OPT/wbc.git
       sh wbc/scripts/install.sh
       
       mkdir -p ros2_ws/src
       cd ros2_ws
       vcs import src --input https://raw.githubusercontent.com/ARC-OPT/wbc_ros/main/repos.yaml
       rosdep install --from-paths src -i -r -y
       colcon build --symlink-install
       source install/setup.bash
       
    # Run all tests
    - name: test
      run: |
        cd ros2_ws
        source install/setup.bash        
        colcon test --packages-select wbc_ros
